services:
  # Development uses SQLite - simpler and more reliable for local development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: agent-system-frontend-dev
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_ENABLE_RAG=true
      - NEXT_PUBLIC_ENABLE_MOCK_FALLBACK=true
      - NEXT_PUBLIC_DEV_MODE=true
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./lib:/app/lib
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./next.config.js:/app/next.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - frontend_node_modules:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - agent-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9999 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agent-system-backend-dev
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/agent_system.db
      - CORS_ORIGINS=http://localhost:9999
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./:/app
      - agent_data:/app/data
      - agent_databases:/app/databases
    networks:
      - agent-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  agent-network:
    driver: bridge

volumes:
  frontend_node_modules:
    driver: local
  agent_data:
    driver: local
  agent_databases:
    driver: local