services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9999:9999"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - agent-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9999 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - CORS_ORIGINS=http://localhost:9999
    volumes:
      - app_data:/app/data
      - ./main.py:/app/main.py
      - ./database:/app/database
      - ./services:/app/services
    networks:
      - agent-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  agent-network:
    driver: bridge

volumes:
  frontend_node_modules:
    driver: local
  app_data:
    driver: local