services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_ENABLE_RAG=true
      - NEXT_PUBLIC_ENABLE_MOCK_FALLBACK=true
      - NEXT_PUBLIC_DEV_MODE=true
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - agent-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///data/agent_system.db
      - CORS_ORIGINS=http://localhost:9999,http://localhost:3000
    volumes:
      - app_data:/app/data
      - ./fastapi-server.py:/app/fastapi-server.py
      - ./database:/app/database
      - ./services:/app/services
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

volumes:
  frontend_node_modules:
    driver: local
  app_data:
    driver: local