version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./data/agent_system.db
    volumes:
      - ./:/app
      - agent_data:/app/data
      - agent_databases:/app/databases
    networks:
      - agent-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9999:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./public:/app/public
      - frontend_node_modules:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - agent-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  agent-network:
    driver: bridge

volumes:
  frontend_node_modules:
    driver: local
  agent_data:
    driver: local
  agent_databases:
    driver: local