app = '6fb-ai-staging'
primary_region = 'ewr'

[build]

[env]
  ENVIRONMENT = 'staging'
  FRONTEND_URL = 'https://6fb-ai-staging.vercel.app'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = 'echo "Deploying 6FB AI Backend"'