[phases.setup]
nixPkgs = ["python310", "nodejs-18_x"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "uvicorn fastapi-server:app --host 0.0.0.0 --port $PORT"