services:
  - type: web
    name: 6fb-ai-backend-staging
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: staging
      - key: FRONTEND_URL
        value: https://6fb-ai-staging.vercel.app
      - key: NODE_ENV
        value: production
    autoDeploy: true

databases:
  - name: 6fb-ai-postgres-staging
    databaseName: 6fb_ai_staging
    user: admin
    plan: free

  - name: 6fb-ai-redis-staging
    plan: free