# Alertmanager Configuration for 6FB AI Agent System
# Comprehensive alert routing and notification management

global:
  # SMTP configuration for email alerts
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@6fb-ai-system.com'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_auth_secret: ''
  smtp_auth_identity: ''

# Inhibit rules - prevent duplicate alerts
inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ['alertname', 'instance']

# Route configuration
route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-receiver'
  routes:
    # Critical alerts - immediate notification
    - matchers:
        - severity="critical"
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 15m

    # Security alerts - immediate notification
    - matchers:
        - category="security"
      receiver: 'security-alerts'
      group_wait: 10s
      repeat_interval: 30m

    # Performance alerts - grouped notifications
    - matchers:
        - category="performance"
      receiver: 'performance-alerts'
      group_interval: 10m
      repeat_interval: 2h

    # Application alerts - business hours
    - matchers:
        - category="application"
      receiver: 'application-alerts'
      group_interval: 5m
      repeat_interval: 1h

    # Business metrics - daily digest
    - matchers:
        - category="business"
      receiver: 'business-alerts'
      group_interval: 1h
      repeat_interval: 24h

    # Infrastructure alerts - maintenance window aware
    - matchers:
        - category="infrastructure"
      receiver: 'infrastructure-alerts'
      group_interval: 15m
      repeat_interval: 4h

# Receivers configuration
receivers:
  # Default receiver (catch-all)
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@6fb-ai-system.com'
        subject: '[6FB AI System] {{ .GroupLabels.alertname }} - {{ .Status | title }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}
        html: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>6FB AI System Alert</title>
          </head>
          <body>
            <h2>6FB AI System Alert Notification</h2>
            {{ range .Alerts }}
            <div style="border: 1px solid #ddd; padding: 10px; margin: 10px 0;">
              <h3 style="color: {{ if eq .Status "firing" }}red{{ else }}green{{ end }};">
                {{ .Annotations.summary }}
              </h3>
              <p><strong>Status:</strong> {{ .Status | title }}</p>
              <p><strong>Description:</strong> {{ .Annotations.description }}</p>
              <p><strong>Time:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
              <details>
                <summary>Labels</summary>
                <ul>
                  {{ range .Labels.SortedPairs }}
                  <li>{{ .Name }}: {{ .Value }}</li>
                  {{ end }}
                </ul>
              </details>
            </div>
            {{ end }}
            <p><small>Generated by 6FB AI Agent System Monitoring</small></p>
          </body>
          </html>

  # Critical alerts receiver
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@6fb-ai-system.com,ops@6fb-ai-system.com'
        subject: '[CRITICAL] 6FB AI System - {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT - IMMEDIATE ACTION REQUIRED 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
          
          Please investigate immediately and take corrective action.
    # Add Slack/Discord/PagerDuty integration here
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#critical-alerts'
    #     title: 'Critical Alert - {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.summary }}: {{ .Annotations.description }}{{ end }}'

  # Security alerts receiver
  - name: 'security-alerts'
    email_configs:
      - to: 'security@6fb-ai-system.com,admin@6fb-ai-system.com'
        subject: '[SECURITY] 6FB AI System - {{ .GroupLabels.alertname }}'
        body: |
          🔒 SECURITY ALERT - REVIEW REQUIRED 🔒
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
          
          Please review security logs and take appropriate action.

  # Performance alerts receiver
  - name: 'performance-alerts'
    email_configs:
      - to: 'ops@6fb-ai-system.com'
        subject: '[PERFORMANCE] 6FB AI System - {{ .GroupLabels.alertname }}'
        body: |
          📊 Performance Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}

  # Application alerts receiver
  - name: 'application-alerts'
    email_configs:
      - to: 'dev@6fb-ai-system.com,ops@6fb-ai-system.com'
        subject: '[APP] 6FB AI System - {{ .GroupLabels.alertname }}'
        body: |
          🔧 Application Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.job }}
          {{ end }}

  # Business alerts receiver
  - name: 'business-alerts'
    email_configs:
      - to: 'business@6fb-ai-system.com'
        subject: '[BUSINESS] 6FB AI System - {{ .GroupLabels.alertname }}'
        body: |
          📈 Business Metrics Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  # Infrastructure alerts receiver
  - name: 'infrastructure-alerts'
    email_configs:
      - to: 'infra@6fb-ai-system.com'
        subject: '[INFRA] 6FB AI System - {{ .GroupLabels.alertname }}'
        body: |
          🏗️ Infrastructure Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}

# Silence configuration (optional)
# silences:
#   - matchers:
#       - alertname="MaintenanceMode"
#     starts_at: "2024-01-01T00:00:00Z"
#     ends_at: "2024-01-01T06:00:00Z"
#     created_by: "admin@6fb-ai-system.com"
#     comment: "Scheduled maintenance window"

# Time intervals for business hours (optional)
time_intervals:
  - name: business-hours
    time_intervals:
      - times:
          - start_time: "09:00"
            end_time: "17:00"
        weekdays: ['monday:friday']
        location: 'America/New_York'

  - name: after-hours
    time_intervals:
      - times:
          - start_time: "17:00"
            end_time: "09:00"
        weekdays: ['monday:friday']
        location: 'America/New_York'
      - weekdays: ['saturday', 'sunday']
        location: 'America/New_York'