name: 6fb-ai-backend-staging
services:
- name: api
  source_dir: /
  github:
    repo: c50bossio/6fb-dashboard-staging
    branch: staging
    deploy_on_push: true
  run_command: gunicorn -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT main:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: ENVIRONMENT
    value: staging
  - key: FRONTEND_URL
    value: https://6fb-ai-staging.vercel.app
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: CORS_ORIGINS
    value: "https://6fb-ai-staging.vercel.app,http://localhost:9999,http://localhost:3000"