# Redis Deployment for AI Response Caching
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: agent-system
  labels:
    app: redis
    component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      component: cache
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --maxmemory
        - "128mb"
        - --maxmemory-policy
        - "allkeys-lru"
        - --save
        - ""
        - --appendonly
        - "no"
        - --tcp-backlog
        - "128"
        - --tcp-keepalive
        - "60"
        - --timeout
        - "300"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "192Mi"
            cpu: "250m"
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: agent-system
spec:
  selector:
    app: redis
    component: cache
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP