# Secret configuration for 6FB AI Agent System
# NOTE: In production, use sealed-secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
  namespace: agent-system
type: Opaque
stringData:
  # Supabase configuration
  NEXT_PUBLIC_SUPABASE_URL: "your-supabase-url"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "your-supabase-anon-key"
  SUPABASE_SERVICE_ROLE_KEY: "your-supabase-service-role-key"
  
  # AI Service Keys
  OPENAI_API_KEY: "your-openai-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"
  GOOGLE_AI_API_KEY: "your-google-ai-api-key"
  
  # Payment Processing
  STRIPE_SECRET_KEY: "your-stripe-secret-key"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "your-stripe-publishable-key"
  
  # Real-time Features
  PUSHER_APP_ID: "your-pusher-app-id"
  PUSHER_SECRET: "your-pusher-secret"
  NEXT_PUBLIC_PUSHER_KEY: "your-pusher-key"
  NEXT_PUBLIC_PUSHER_CLUSTER: "your-pusher-cluster"
  
  # JWT Secret
  JWT_SECRET_KEY: "your-jwt-secret-key-minimum-32-characters"
  
  # Database credentials (if using external DB)
  DATABASE_URL: "postgresql://user:password@host:5432/dbname"