services:
  # Development uses SQLite - simpler and more reliable for local development
  # Redis for AI response caching - reduces AI API costs by 60-70%
  
  redis:
    image: redis:7.2-alpine
    container_name: agent-system-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - agent-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: agent-system-frontend-dev
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - FASTAPI_BASE_URL=http://backend:8000
      - NEXT_PUBLIC_ENABLE_RAG=true
      - NEXT_PUBLIC_ENABLE_MOCK_FALLBACK=true
      # DISABLED: Dev mode was causing automatic login with test user
      # - NEXT_PUBLIC_DEV_MODE=true
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=587
    env_file:
      - .env.local
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./hooks:/app/hooks
      - ./lib:/app/lib
      - ./public:/app/public
      - ./styles:/app/styles
      - ./package.json:/app/package.json
      - ./next.config.js:/app/next.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - frontend_node_modules:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - agent-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9999 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agent-system-backend-dev
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - CORS_ORIGINS=http://localhost:9999
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379
      - USE_FASTAPI=true
      - USE_SUPABASE=true
      - DOCKER_ENVIRONMENT=true
    env_file:
      - .env.local
    volumes:
      - ./:/app
      - agent_data:/app/data
      - agent_databases:/app/databases
    depends_on:
      - redis
    networks:
      - agent-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  agent-network:
    driver: bridge

volumes:
  frontend_node_modules:
    driver: local
  agent_data:
    driver: local
  agent_databases:
    driver: local
  redis_data:
    driver: local